#!/usr/local/bin/perl

$ra0=35.8748;
$dec0=0.08691666666;

system("wget --no-clobber http://www.astro.utoronto.ca/~cnoc/cnoc2_0223_20010213.tar.gz");
system("tar -xvzf cnoc2_0223_20010213.tar.gz");

open(fp,"<cnoc2_0223_20010213.dat");
$started=0;
$num=0;
while(<fp>) {
	chomp;
	split;
	if($_[0] eq "#PPPID") {
		$started=1;
		for($i=0;$i<@_;$i++) {
			if($_[$i] eq "d_RA") {
				$ioRa=$i;
			}
			if($_[$i] eq "d_Dec") {
				$ioDec=$i;
			}
			if($_[$i] eq "z") {
				$iz=$i;
			}
			if($_[$i] eq "Rval") {
				$iRval=$i;
			}
			if($_[$i] eq "Sc") {
				$iSc=$i;
			}
			if($_[$i] eq "Imag") {
				$iImag=$i;
			}
			if($_[$i] eq "Ime") {
				$iIme=$i;
			}
			if($_[$i] eq "Umag") {
				$iUmag=$i;
			}
			if($_[$i] eq "Ume") {
				$iUme=$i;
			}
			if($_[$i] eq "Bmag") {
				$iBmag=$i;
			}
			if($_[$i] eq "Bme") {
				$iBme=$i;
			}
			if($_[$i] eq "Vmag") {
				$iVmag=$i;
			}
			if($_[$i] eq "Vme") {
				$iVme=$i;
			}
			if($_[$i] eq "Rmag") {
				$iRmag=$i;
			}
			if($_[$i] eq "Rme") {
				$iRme=$i;
			}
		}
	} elsif($started) {
		$oRa[$num]=$_[$ioRa];
		$oDec[$num]=$_[$ioDec];
		$z[$num]=$_[$iz];
		$Rval[$num]=$_[$iRval];
		$Sc[$num]=$_[$iSc];
		$Imag[$num]=$_[$iImag];
		$Ime[$num]=$_[$iIme];
		$Umag[$num]=$_[$iUmag];
		$Ume[$num]=$_[$iUme];
		$Vmag[$num]=$_[$iVmag];
		$Vme[$num]=$_[$iVme];
		$Bmag[$num]=$_[$iBmag];
		$Bme[$num]=$_[$iBme];
		$Rmag[$num]=$_[$iRmag];
		$Rme[$num]=$_[$iRme];
		if($z[$num] < 9. && ($Rval[$num]>5. || 
												 ($Rval[$num]>4. and $Sc[$num]!=5))) {
			$num++;
		}
	}
}
close(fp);

open(fp,">cnoc2.par");
print fp <<EOF;
typedef struct {
  double z;
  double ra1950;
  double dec1950;
  double Rval;
  double Sc;
  double UBVRI[5];
  double UBVRI_ivar[5];
} CNOC2STR;

EOF
for($i=0;$i<$num;$i++) {
	$dec=$dec0+$oDec[$i]/3600.;
	$ra=$ra0-$oRa[$i]/3600./cos($dec*3.14159265/180.);
	printf fp "CNOC2STR %e %e %e %e %d ", $z[$i], $ra, $dec, $Rval[$i], $Sc[$i];
	printf fp " { %e %e %e %e %e } ", $Umag[$i], $Bmag[$i], $Vmag[$i], 
	$Rmag[$i], $Imag[$i];
	$Umag_ivar=1./($Ume[$i]*0.01)/($Ume[$i]*0.01);
	$Bmag_ivar=1./($Bme[$i]*0.01)/($Bme[$i]*0.01);
	$Vmag_ivar=1./($Vme[$i]*0.01)/($Vme[$i]*0.01);
	$Rmag_ivar=1./($Rme[$i]*0.01)/($Rme[$i]*0.01);
	$Imag_ivar=1./($Ime[$i]*0.01)/($Ime[$i]*0.01);
	printf fp " { %e %e %e %e %e }\n", $Umag_ivar, $Bmag_ivar, $Vmag_ivar, 
	$Rmag_ivar, $Imag_ivar;
}
close(fp);

open(pp,"|idl");
print pp <<EOF;
a=yanny_readone('cnoc2.par') 
b1=create_struct(a[0],'ra',0.D,'dec',0.D)
b=replicate(b1,n_elements(a))
struct_assign,a,b
jprecess,b.ra1950,b.dec1950,ra,dec
b.ra=ra
b.dec=dec
mwrfits,b,'cnoc2.fits',/create
obj=sdss_findobj(b.ra,b.dec,dmax=10./3600.,rerun=131,childobj=childobj)
mwrfits,obj,'cnoc2-obj.fits',/create
mwrfits,childobj,'cnoc2-childobj.fits',/create
help,where(obj.matchdist*3600. lt 10.)
EOF
		close(pp);
