###############################################################################
# Sloan Digital Sky Survey (SDSS)
#
# M. Blanton
###############################################################################

#
# IDL support utilities for spectro2d and the fibermapper
#
SHELL = /bin/sh
#
# Install things in their proper places in $(KCORRECT_DIR)
#
all:
	
install :
	 
#
clean :
