###############################################################################
# Sloan Digital Sky Survey (SDSS)
#
# M. Blanton
###############################################################################

#
SHELL = /bin/sh
#
# Install things in their proper places in $(KCORRECT_DIR)
#
all:

install :
	- cp README sample.dat sample.fits $(KCORRECT_DIR)/test
#
clean :
