#!/usr/local/bin/perl

$minf=0.98;
$maxf=1.00;
$num=21;
for($i=0;$i<$num;$i++) {
	$factor=$minf+$i*($maxf-$minf)/($num-1);
	$factor4=sprintf("%5.3f",$factor);

	system("cd ../data/filters ; scalefilters $factor");
	system("cat testsp.K.dat | fit_coeffs scale > testsp.K.coeffs.scale.dat");
	system("cat testsp.K.coeffs.scale.dat | reconstruct_maggies -1. scale > testsp.K.maggies.scale.dat");
	system("cat testsp.K.coeffs.scale.dat | reconstruct_maggies 0.01 scale > testsp.K.maggies.z0.scale.dat");
	system("smrun -nsf ugr.$factor4.ps ugr.sm");
	system("psgif -a ugr.$factor4.ps > ugr.$factor4.gif");
	@filelist=(@filelist,"ugr.$factor4.gif");
}
	
system("gifmerge -l0 -10 @filelist > ugr.anim.gif");
