#!/usr/bin/env python

import os
import re

import astropy.table
import pydl.pydlutils.yanny

files = os.listdir(".")

for file in files:
    if(re.match("^.*\.par$", file) is not None):
        r = pydl.pydlutils.yanny.yanny(file)
        k = list(r.keys())[0]
        t = astropy.table.Table(r[k])
        fp = open(file)
        comments = []
        for line in fp.readlines():
            m = re.match(r"^#\s?(.*)\n$", line)
            if(m is not None):
                comments += [m.group(1)]
        t.meta['comments'] = comments
        fp.close()
        efile = file.replace(".par", ".dat")
        t.write(efile, format='ascii.fixed_width',
                overwrite=True)
