###############################################################################
# kcorrect
###############################################################################

SHELL = /bin/sh
#
all :;

install :
	- cp kcorrect.table $(KCORRECT_DIR)/ups
	- cp Makefile $(KCORRECT_DIR)/ups

clean :
	rm -f *~ core *.bak *.orig *.old .#* #*#
