#!/bin/csh -f 

curl http://deep.berkeley.edu/DR1/zcat.dr1.uniq.fits.gz >! $KCORRECT_DIR/data/redshifts/deep/zcat.dr1.uniq.fits.gz

curl http://deep.berkeley.edu/DR1/pcat.11.fits.gz >! $KCORRECT_DIR/data/redshifts/deep/pcat.11.fits.gz
curl http://deep.berkeley.edu/DR1/pcat.12.fits.gz >! $KCORRECT_DIR/data/redshifts/deep/pcat.12.fits.gz
curl http://deep.berkeley.edu/DR1/pcat.13.fits.gz >! $KCORRECT_DIR/data/redshifts/deep/pcat.13.fits.gz
curl http://deep.berkeley.edu/DR1/pcat.14.fits.gz >! $KCORRECT_DIR/data/redshifts/deep/pcat.14.fits.gz

curl http://deep.berkeley.edu/DR1/pcat.21.fits.gz >! $KCORRECT_DIR/data/redshifts/deep/pcat.21.fits.gz
curl http://deep.berkeley.edu/DR1/pcat.22.fits.gz >! $KCORRECT_DIR/data/redshifts/deep/pcat.22.fits.gz
curl http://deep.berkeley.edu/DR1/pcat.23.fits.gz >! $KCORRECT_DIR/data/redshifts/deep/pcat.23.fits.gz

curl http://deep.berkeley.edu/DR1/pcat.31.fits.gz >! $KCORRECT_DIR/data/redshifts/deep/pcat.31.fits.gz
curl http://deep.berkeley.edu/DR1/pcat.32.fits.gz >! $KCORRECT_DIR/data/redshifts/deep/pcat.32.fits.gz
curl http://deep.berkeley.edu/DR1/pcat.33.fits.gz >! $KCORRECT_DIR/data/redshifts/deep/pcat.33.fits.gz

curl http://deep.berkeley.edu/DR1/pcat.41.fits.gz >! $KCORRECT_DIR/data/redshifts/deep/pcat.41.fits.gz
curl http://deep.berkeley.edu/DR1/pcat.42.fits.gz >! $KCORRECT_DIR/data/redshifts/deep/pcat.42.fits.gz
curl http://deep.berkeley.edu/DR1/pcat.43.fits.gz >! $KCORRECT_DIR/data/redshifts/deep/pcat.43.fits.gz
