#!/usr/bin/perl

#
# Give the directory with the JEG results, and it 
# extracts the 1.3 airmass results, putting them
# into the filter format used.
#

$jegdir=shift;
@bands=("u", "g", "r", "i", "z");
foreach $band (@bands) {
	for($col=0;$col<7;$col++) {
		print "$jegdir/sdss_$band$col.res\n";
		open(ifp,"$jegdir/sdss_$band$col.res");
		open(ofp,">./sdss_$band$col.dat");
		$nlines=0;
		while(<ifp>) {
			if(!/^\#/ && !/^\\/) {
				chop;
				split;
				$lambda[$nlines]=$_[0];
				$pass[$nlines]=$_[3];
				$nlines++;	
			}
		}
		printf ofp "%d\n",$nlines;
		for($i=0;$i<$nlines;$i++) {
			printf ofp "%e %e\n",$lambda[$i], $pass[$i];
		}
		close(ofp);
		close(ifp);
	}
}
