#!/usr/bin/perl -w 

#
# Give the directory with the JEG results, and it 
# extracts the 1.3 airmass results, putting them
# into the filter format used.
#

@bands=("u", "g", "r", "i", "z");
$jegdir="sdss";
foreach $band (@bands) {
	for($col=0;$col<7;$col++) {
		print "$jegdir/sdss_$band$col.res\n";

		open(ifp,"$jegdir/sdss_$band$col.res");
		$nlines=0;
		while(<ifp>) {
			if(!/^\#/ && !/^\\/) {
				$nlines++;	
			}
		}

		open(ofp,">./sdss_$band$col.dat");
		open(ifp,"sdssheader");
		$colname="Column $col";
		if($col == 0) {
			$colname="Average over columns 1-6";
		}
		while(<ifp>) {
			s/\[SPECIFY\]/$band/g;	
			s/\[SPECIFY: WHICH COLUMN\]/$colname/g;	
			print ofp;
		}
		close(ifp);
		printf ofp "%d 6 3\n",$nlines;
		open(ifp,"$jegdir/sdss_$band$col.res");
		while(<ifp>) {
			print ofp;
		}
		close(ifp);
		close(ofp);
	}
}
