#!/usr/bin/perl 

#
# Give the directory with the JEG results, and it 
# extracts the 1.3 airmass results, putting them
# into the filter format used.
#

@bands=("B","V","R","I");
$besselldir="bessell";
foreach $band (@bands) {
	print "$besselldir/bessell_${band}.dat\n";
	
	open(ifp,"$besselldir/bessell_${band}.dat");
	$nlines=0;
	while(<ifp>) {
		chop;
		split;
		if($_[0]>0) {
			$nlines++;	
		}
	}
	
	open(ofp,">./bessell_$band.dat");
	open(ifp,"bessellheader");
	while(<ifp>) {
		s/\[SPECIFY\]/$band/g;	
		print ofp;
	}
	close(ifp);
	printf ofp "%d 2 2\n",$nlines;
	open(ifp,"$besselldir/bessell_${band}.dat");
	while(<ifp>) {
		$line=$_;
		chop;
		split;
		if($_[0]>0) {
			print ofp "$line";
		} else {
			print ofp "# $line";
		}
	}
	close(ifp);
	close(ofp);
}
